platform :ios, '9.0' 
target 'PolySoftRN' do
 pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'CxxBridge',
  'RCTLinkingIOS'
  ]
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # ios9.0以上版本才行
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'SDWebImage', '~>4.0.0'
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'

  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'




  pod 'JAnalyticsRN', :path => '../node_modules/janalytics-react-native'

end
